apiVersion: v1
kind: ConfigMap
metadata:
  name: paybck-env
data:
  APP_NAME: Laravel
  APP_ENV: local
  #APP_KEY: 'V5RyOROBxEFCV0LY1VlbEKjBF6f/L9jh0yko9IR5fJM:'
  APP_DEBUG: 'true'
  APP_URL: 'https://laravel.autofacildespachante.com/'

  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: 'null'
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: pay-mysql-svc
  DB_PORT: '3306'
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: laravel@123

  DB_CONNECTION_LOG: mysql
  DB_HOST_LOG: pay-mysql-svc
  DB_PORT_LOG: '3306'
  DB_DATABASE_LOG: laravel_log
  DB_USERNAME_LOG: root
  DB_PASSWORD_LOG: laravel@123
  ACTIVITY_LOGGER_ENABLED: 'false'
  ACTIVITY_LOGGER_DB_CONNECTION: db_log

  KEYCLOAK_CLIENT_ID: autofacil
  KEYCLOAK_CLIENT_SECRET:
  KEYCLOAK_REDIRECT_URI: 'https://auth.autofacildespachante.com/auth/login/callback'
  KEYCLOAK_BASE_URL: 'https://auth.autofacildespachante.com/auth'
  KEYCLOAK_REALM: production