apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-backend
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
  labels:
    app: pay-backend
spec:
  selector:
    matchLabels:
      app: pay-backend
  replicas: 1
  strategy:
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: "pay-backend"
    spec:
      containers:
        - name: pay-backend
          image: fernandoomarcelino/app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: paybck-env          
          ports:
          - containerPort: 80
          resources:
            requests: 
              cpu: "100m"
              memory: 100Mi
            limits:
              cpu: "200m"
              memory: 200Mi    