apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  annotations:
    cloud.google.com/neg: '{"ingress": false}'  
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
#        image: quay.io/keycloak/keycloak:20.0.3
#        image: quay.io/keycloak/keycloak:10.0.1
        image: bitnami/keycloak
#        args: ["start"]
#        args: ["start-dev"]
#        build --db=mysql  
        envFrom:
          - configMapRef:
              name: keycloak-env
#          - secretRef:
#              name: keycloak-secret
        ports:
        - name: http
          containerPort: 8080
#        readinessProbe:
#          httpGet:
#            path: /realms/master
#            port: 8080          
        resources:
          requests: 
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi" 