apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-frontend
#  annotations:
#    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: pay-frontend
spec:
  selector:
    matchLabels:
      app: pay-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: "pay-frontend"
    spec:
      containers:
        - name: pay-frontend
          image: murilobauer90/app-payment:latest
          ports:
          - containerPort: 80
          resources:
            requests: 
              cpu: "0.08"
              memory: 100Mi
            limits:
              cpu: "0.08"
              memory: 100Mi        