apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-frontend
#  annotations:
#    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: pay-frontend
spec:
  selector:
    matchLabels:
      app: pay-frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "pay-frontend"
    spec:
      containers:
        - name: pay-frontend
          image: gcr.io/production-376800/payment_app_gpc:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests: 
              cpu: "100m"
              memory: 100Mi
            limits:
              cpu: "200m"
              memory: 200Mi