apiVersion: v1
kind: PersistentVolume
metadata:
  name: lrv-mysql-pv-volume
spec:
#  storageClassName: storageclasse-gce-provision
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
#    path: "/mnt/data"
    path: "/var/lib/mysql"