apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-backend
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
  labels:
    app: laravel-backend
spec:
  selector:
    matchLabels:
      app: laravel-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "laravel-backend"
    spec:
      containers:
        - name: laravel-backend
          image: laravelsail/php81-composer:latest
          ports:
          - containerPort: 8082
          resources:
            requests: 
              cpu: "0.08"
              memory: 100Mi
            limits:
              cpu: "0.08"
              memory: 100Mi        