apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
  - name: laravel-service
    port: 80
    targetPort: 8082
    protocol: TCP