apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-mysql
spec:
  selector:
    matchLabels:
      app: pay-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pay-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: pay-mysql
        envFrom:
          - configMapRef:
              name: pay-mysql-env
        ports:
        - containerPort: 3306
          name: pay-mysql-svc
        resources:
          requests: 
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "1024Mi"         
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pay-mysql-pv-claim