apiVersion: v1
kind: Service
metadata:
  name: pay-mysql-svc
spec:
  ports:
  - name: pay-mysql-svc
    port: 3306
    targetPort: 3306
  selector:
    app: pay-mysql
  #clusterIP: None
  type: ClusterIP