##pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
spec:
#  storageClassName: storageclasse-gce-provision
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"