apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-svc
spec:
  ports:
  - name: wordpress
    port: 8081
    targetPort: 80
  selector:
    app: wordpress
#    tier: frontend
  type: NodePort