apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-cloudflare
  namespace: default
spec:
  secretName: cert-cloudflare
  issuerRef:
    name: letsencrypt-cloudflare-production
    #kind: ClusterIssuer
  dnsNames:
  - '*.autofacildespachante.com'
  - autofacildespachante.com