apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cloudflare-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: murilo.bauer90@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare-staging
    solvers:
    - dns01:
        cloudflare:
          email: murilo.bauer90@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
#      selector:
#        dnsZones:
#        - '*.autofacildespachante.com'
#        - autofacildespachante.com