apiVersion: v1
kind: Service
metadata:
  name: wp-mysql-svc
spec:
  ports:
  - name: wp-mysql-svc
    port: 3306
    targetPort: 3306
  selector:
    app: wp-mysql
  clusterIP: None
  #type: ClusterIP