apiVersion: apps/v1
kind: Deployment
metadata:
  name: site1
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
  labels:
    app: site1
spec:
  selector:
    matchLabels:
      app: site1
  replicas: 1
  template:
    metadata:
      labels:
        app: "site1"
    spec:
      containers:
        - name: site1
          image: paulbouwer/hello-kubernetes:1.5
          ports:
          - containerPort: 8080
          resources:
            requests: 
              cpu: "100m"
              memory: 100Mi
            limits:
              cpu: "200m"
              memory: 200Mi     