apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
    #kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: ssl-redirect
    cert-manager.io/issuer: "letsencrypt-cloudflare-production"
spec:
  tls:
    - secretName: cert-cloudflare
#      hosts:
#        - "*.autofacildespachante.com"
#        - autofacildespachante.com
#        - www.autofacildespachante.com
#        - site1.autofacildespachante.com
#        - site2.autofacildespachante.com
#        - auth.autofacildespachante.com
  defaultBackend:
    service:
      name: site1-service
      port:
        number: 80
  rules:
  - host: "site1.autofacildespachante.com"
    http:
      paths:
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: site1-service
            port:
              number: 80
  - host: "auth.autofacildespachante.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080