apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-mysql
spec:
  selector:
    matchLabels:
      app: key-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: key-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: key-mysql
        envFrom:
          - configMapRef:
              name: key-mysql-env
        ports:
        - containerPort: 3306
          name: key-mysql-svc
        resources:
          requests: 
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "1024Mi"          
        volumeMounts:
        - name: key-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: key-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: key-mysql-pv-claim