kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: key-mysql-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#  storageClassName: storageclasse-gce-provision