apiVersion: v1
kind: Service
metadata:
  name: key-mysql-svc
spec:
  ports:
  - name: key-mysql-svc
    port: 3306
    targetPort: 3306
  selector:
    app: key-mysql
  #clusterIP: None
  type: ClusterIP